version: "3.8"

services:
  reth-db-reader:
    build: .
    image: reth-db-reader:latest
    volumes:
      - reth_mainnet_data:/root/.local/share/reth/mainnet
    environment:
      - RETH_DB_PATH=/root/.local/share/reth/mainnet

volumes:
  reth_mainnet_data:
    external: true
